package com.agri.supplytracker.traceability.domain;
public enum TraceEventType { BATCH_CREATED, STATUS_CHANGED, LEGACY_IMPORTED, CUSTODY_OFFERED, CUSTODY_ACCEPTED, SHIPMENT_DISPATCHED, COLD_CHAIN_EXCURSION, SHIPMENT_RECEIVED, LINEAGE_SPLIT, LINEAGE_MERGE, LINEAGE_DERIVE, LINEAGE_CONSUME, RECALL_CASE_CREATED, RECALL_CASE_RESOLVED }
