package com.agri.supplytracker.traceability.domain;
public enum TraceEventType { BATCH_CREATED, STATUS_CHANGED, LEGACY_IMPORTED, CUSTODY_OFFERED, CUSTODY_ACCEPTED, SHIPMENT_DISPATCHED, COLD_CHAIN_EXCURSION, SHIPMENT_RECEIVED }
